#!/usr/bin/env node
import { readdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = join(__dirname, '..')

// Get all icon names from lucide-static
const iconsDir = join(rootDir, 'node_modules/lucide-static/icons')
const iconFiles = readdirSync(iconsDir)
const iconNames = iconFiles
  .filter((file) => file.endsWith('.svg'))
  .map((file) => file.replace('.svg', ''))
  .sort()

// Generate the TypeScript type
const typeContent = `// This file is auto-generated by scripts/generate-types.mjs
// Do not edit manually - run 'npm run generate:types' to regenerate

/**
 * Available Lucide icon names
 * Total icons: ${iconNames.length}
 */
export type IconName =
${iconNames.map((name) => `  | '${name}'`).join('\n')}
`

// Write the type file
const typesPath = join(rootDir, 'src/types.ts')
writeFileSync(typesPath, typeContent, 'utf-8')

console.log(`✅ Generated ${iconNames.length} icon names in src/types.ts`)
